# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Beguda.create([
  { :preuTall => nil, :preuGrande => nil, :preuVenti => nil, :created_at => nil, :updated_at => nil, :nom => nil }
])



Botiga.create([
  { :pass => nil, :lat => nil, :lang => nil, :created_at => nil, :updated_at => nil }
])



Comanda.create([
  { :usuari_id => nil, :beguda_id => nil, :feta => nil, :created_at => nil, :updated_at => nil }
])



Extra.create([
  { :nom => nil, :preu => nil, :created_at => nil, :updated_at => nil }
])



ExtraDisponible.create([
  { :beguda_id => nil, :extra_id => nil, :created_at => nil, :updated_at => nil }
])



Toping.create([
  { :comanda_id => nil, :extra_id => nil, :created_at => nil, :updated_at => nil }
])



Usuari.create([
  { :nom => nil, :pass => nil, :saldo => nil, :created_at => nil, :updated_at => nil }
])


